import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets:["latin"], 
  weight:["400", "300", "500", "600" ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >

        <main className="mx-10 sm:mx-20 md:mx-30 lg:mx-50 mt-10">
      {children}
        </main>
  
      </body>
    </html>
  );
}
